/* Autogenerated file. Do not edit manually. */
/* tslint:disable */
/* eslint-disable */
import type {
  BaseContract,
  BigNumberish,
  BytesLike,
  FunctionFragment,
  Result,
  Interface,
  EventFragment,
  AddressLike,
  ContractRunner,
  ContractMethod,
  Listener,
} from "ethers";
import type {
  TypedContractEvent,
  TypedDeferredTopicFilter,
  TypedEventLog,
  TypedLogDescription,
  TypedListener,
  TypedContractMethod,
} from "../common";

export declare namespace WaterPureLog {
  export type UserSummaryStruct = {
    totalTds: BytesLike;
    totalPh: BytesLike;
    totalConductivity: BytesLike;
    totalHardness: BytesLike;
    count: BigNumberish;
    lastRating: BigNumberish;
  };

  export type UserSummaryStructOutput = [
    totalTds: string,
    totalPh: string,
    totalConductivity: string,
    totalHardness: string,
    count: bigint,
    lastRating: bigint
  ] & {
    totalTds: string;
    totalPh: string;
    totalConductivity: string;
    totalHardness: string;
    count: bigint;
    lastRating: bigint;
  };

  export type WaterRecordStruct = {
    tds: BytesLike;
    ph: BytesLike;
    conductivity: BytesLike;
    hardness: BytesLike;
    rating: BigNumberish;
    timestamp: BigNumberish;
  };

  export type WaterRecordStructOutput = [
    tds: string,
    ph: string,
    conductivity: string,
    hardness: string,
    rating: bigint,
    timestamp: bigint
  ] & {
    tds: string;
    ph: string;
    conductivity: string;
    hardness: string;
    rating: bigint;
    timestamp: bigint;
  };
}

export interface WaterPureLogInterface extends Interface {
  getFunction(
    nameOrSignature:
      | "checkAllBadgeEligibility"
      | "checkBadgeEligibility"
      | "claimBadge"
      | "confidentialProtocolId"
      | "getEncryptedSummary"
      | "getLastRecordInfo"
      | "getRatingHistory"
      | "getRecord"
      | "getRecordCount"
      | "getUserBadges"
      | "submitRecord"
  ): FunctionFragment;

  getEvent(
    nameOrSignatureOrTopic: "BadgeClaimed" | "RecordSubmitted"
  ): EventFragment;

  encodeFunctionData(
    functionFragment: "checkAllBadgeEligibility",
    values: [AddressLike]
  ): string;
  encodeFunctionData(
    functionFragment: "checkBadgeEligibility",
    values: [AddressLike, BigNumberish]
  ): string;
  encodeFunctionData(
    functionFragment: "claimBadge",
    values: [BigNumberish]
  ): string;
  encodeFunctionData(
    functionFragment: "confidentialProtocolId",
    values?: undefined
  ): string;
  encodeFunctionData(
    functionFragment: "getEncryptedSummary",
    values: [AddressLike]
  ): string;
  encodeFunctionData(
    functionFragment: "getLastRecordInfo",
    values: [AddressLike]
  ): string;
  encodeFunctionData(
    functionFragment: "getRatingHistory",
    values: [AddressLike]
  ): string;
  encodeFunctionData(
    functionFragment: "getRecord",
    values: [AddressLike, BigNumberish]
  ): string;
  encodeFunctionData(
    functionFragment: "getRecordCount",
    values: [AddressLike]
  ): string;
  encodeFunctionData(
    functionFragment: "getUserBadges",
    values: [AddressLike]
  ): string;
  encodeFunctionData(
    functionFragment: "submitRecord",
    values: [
      BytesLike,
      BytesLike,
      BytesLike,
      BytesLike,
      BigNumberish,
      BytesLike
    ]
  ): string;

  decodeFunctionResult(
    functionFragment: "checkAllBadgeEligibility",
    data: BytesLike
  ): Result;
  decodeFunctionResult(
    functionFragment: "checkBadgeEligibility",
    data: BytesLike
  ): Result;
  decodeFunctionResult(functionFragment: "claimBadge", data: BytesLike): Result;
  decodeFunctionResult(
    functionFragment: "confidentialProtocolId",
    data: BytesLike
  ): Result;
  decodeFunctionResult(
    functionFragment: "getEncryptedSummary",
    data: BytesLike
  ): Result;
  decodeFunctionResult(
    functionFragment: "getLastRecordInfo",
    data: BytesLike
  ): Result;
  decodeFunctionResult(
    functionFragment: "getRatingHistory",
    data: BytesLike
  ): Result;
  decodeFunctionResult(functionFragment: "getRecord", data: BytesLike): Result;
  decodeFunctionResult(
    functionFragment: "getRecordCount",
    data: BytesLike
  ): Result;
  decodeFunctionResult(
    functionFragment: "getUserBadges",
    data: BytesLike
  ): Result;
  decodeFunctionResult(
    functionFragment: "submitRecord",
    data: BytesLike
  ): Result;
}

export namespace BadgeClaimedEvent {
  export type InputTuple = [
    user: AddressLike,
    badgeType: BigNumberish,
    timestamp: BigNumberish
  ];
  export type OutputTuple = [
    user: string,
    badgeType: bigint,
    timestamp: bigint
  ];
  export interface OutputObject {
    user: string;
    badgeType: bigint;
    timestamp: bigint;
  }
  export type Event = TypedContractEvent<InputTuple, OutputTuple, OutputObject>;
  export type Filter = TypedDeferredTopicFilter<Event>;
  export type Log = TypedEventLog<Event>;
  export type LogDescription = TypedLogDescription<Event>;
}

export namespace RecordSubmittedEvent {
  export type InputTuple = [
    user: AddressLike,
    recordIndex: BigNumberish,
    rating: BigNumberish,
    timestamp: BigNumberish
  ];
  export type OutputTuple = [
    user: string,
    recordIndex: bigint,
    rating: bigint,
    timestamp: bigint
  ];
  export interface OutputObject {
    user: string;
    recordIndex: bigint;
    rating: bigint;
    timestamp: bigint;
  }
  export type Event = TypedContractEvent<InputTuple, OutputTuple, OutputObject>;
  export type Filter = TypedDeferredTopicFilter<Event>;
  export type Log = TypedEventLog<Event>;
  export type LogDescription = TypedLogDescription<Event>;
}

export interface WaterPureLog extends BaseContract {
  connect(runner?: ContractRunner | null): WaterPureLog;
  waitForDeployment(): Promise<this>;

  interface: WaterPureLogInterface;

  queryFilter<TCEvent extends TypedContractEvent>(
    event: TCEvent,
    fromBlockOrBlockhash?: string | number | undefined,
    toBlock?: string | number | undefined
  ): Promise<Array<TypedEventLog<TCEvent>>>;
  queryFilter<TCEvent extends TypedContractEvent>(
    filter: TypedDeferredTopicFilter<TCEvent>,
    fromBlockOrBlockhash?: string | number | undefined,
    toBlock?: string | number | undefined
  ): Promise<Array<TypedEventLog<TCEvent>>>;

  on<TCEvent extends TypedContractEvent>(
    event: TCEvent,
    listener: TypedListener<TCEvent>
  ): Promise<this>;
  on<TCEvent extends TypedContractEvent>(
    filter: TypedDeferredTopicFilter<TCEvent>,
    listener: TypedListener<TCEvent>
  ): Promise<this>;

  once<TCEvent extends TypedContractEvent>(
    event: TCEvent,
    listener: TypedListener<TCEvent>
  ): Promise<this>;
  once<TCEvent extends TypedContractEvent>(
    filter: TypedDeferredTopicFilter<TCEvent>,
    listener: TypedListener<TCEvent>
  ): Promise<this>;

  listeners<TCEvent extends TypedContractEvent>(
    event: TCEvent
  ): Promise<Array<TypedListener<TCEvent>>>;
  listeners(eventName?: string): Promise<Array<Listener>>;
  removeAllListeners<TCEvent extends TypedContractEvent>(
    event?: TCEvent
  ): Promise<this>;

  checkAllBadgeEligibility: TypedContractMethod<
    [user: AddressLike],
    [boolean[]],
    "view"
  >;

  checkBadgeEligibility: TypedContractMethod<
    [user: AddressLike, badgeType: BigNumberish],
    [boolean],
    "view"
  >;

  claimBadge: TypedContractMethod<
    [badgeType: BigNumberish],
    [void],
    "nonpayable"
  >;

  confidentialProtocolId: TypedContractMethod<[], [bigint], "view">;

  getEncryptedSummary: TypedContractMethod<
    [user: AddressLike],
    [WaterPureLog.UserSummaryStructOutput],
    "view"
  >;

  getLastRecordInfo: TypedContractMethod<
    [user: AddressLike],
    [[bigint, bigint] & { rating: bigint; timestamp: bigint }],
    "view"
  >;

  getRatingHistory: TypedContractMethod<
    [user: AddressLike],
    [bigint[]],
    "view"
  >;

  getRecord: TypedContractMethod<
    [user: AddressLike, index: BigNumberish],
    [WaterPureLog.WaterRecordStructOutput],
    "view"
  >;

  getRecordCount: TypedContractMethod<[user: AddressLike], [bigint], "view">;

  getUserBadges: TypedContractMethod<[user: AddressLike], [boolean[]], "view">;

  submitRecord: TypedContractMethod<
    [
      tds: BytesLike,
      ph: BytesLike,
      conductivity: BytesLike,
      hardness: BytesLike,
      rating: BigNumberish,
      inputProof: BytesLike
    ],
    [void],
    "nonpayable"
  >;

  getFunction<T extends ContractMethod = ContractMethod>(
    key: string | FunctionFragment
  ): T;

  getFunction(
    nameOrSignature: "checkAllBadgeEligibility"
  ): TypedContractMethod<[user: AddressLike], [boolean[]], "view">;
  getFunction(
    nameOrSignature: "checkBadgeEligibility"
  ): TypedContractMethod<
    [user: AddressLike, badgeType: BigNumberish],
    [boolean],
    "view"
  >;
  getFunction(
    nameOrSignature: "claimBadge"
  ): TypedContractMethod<[badgeType: BigNumberish], [void], "nonpayable">;
  getFunction(
    nameOrSignature: "confidentialProtocolId"
  ): TypedContractMethod<[], [bigint], "view">;
  getFunction(
    nameOrSignature: "getEncryptedSummary"
  ): TypedContractMethod<
    [user: AddressLike],
    [WaterPureLog.UserSummaryStructOutput],
    "view"
  >;
  getFunction(
    nameOrSignature: "getLastRecordInfo"
  ): TypedContractMethod<
    [user: AddressLike],
    [[bigint, bigint] & { rating: bigint; timestamp: bigint }],
    "view"
  >;
  getFunction(
    nameOrSignature: "getRatingHistory"
  ): TypedContractMethod<[user: AddressLike], [bigint[]], "view">;
  getFunction(
    nameOrSignature: "getRecord"
  ): TypedContractMethod<
    [user: AddressLike, index: BigNumberish],
    [WaterPureLog.WaterRecordStructOutput],
    "view"
  >;
  getFunction(
    nameOrSignature: "getRecordCount"
  ): TypedContractMethod<[user: AddressLike], [bigint], "view">;
  getFunction(
    nameOrSignature: "getUserBadges"
  ): TypedContractMethod<[user: AddressLike], [boolean[]], "view">;
  getFunction(
    nameOrSignature: "submitRecord"
  ): TypedContractMethod<
    [
      tds: BytesLike,
      ph: BytesLike,
      conductivity: BytesLike,
      hardness: BytesLike,
      rating: BigNumberish,
      inputProof: BytesLike
    ],
    [void],
    "nonpayable"
  >;

  getEvent(
    key: "BadgeClaimed"
  ): TypedContractEvent<
    BadgeClaimedEvent.InputTuple,
    BadgeClaimedEvent.OutputTuple,
    BadgeClaimedEvent.OutputObject
  >;
  getEvent(
    key: "RecordSubmitted"
  ): TypedContractEvent<
    RecordSubmittedEvent.InputTuple,
    RecordSubmittedEvent.OutputTuple,
    RecordSubmittedEvent.OutputObject
  >;

  filters: {
    "BadgeClaimed(address,uint8,uint256)": TypedContractEvent<
      BadgeClaimedEvent.InputTuple,
      BadgeClaimedEvent.OutputTuple,
      BadgeClaimedEvent.OutputObject
    >;
    BadgeClaimed: TypedContractEvent<
      BadgeClaimedEvent.InputTuple,
      BadgeClaimedEvent.OutputTuple,
      BadgeClaimedEvent.OutputObject
    >;

    "RecordSubmitted(address,uint256,uint8,uint256)": TypedContractEvent<
      RecordSubmittedEvent.InputTuple,
      RecordSubmittedEvent.OutputTuple,
      RecordSubmittedEvent.OutputObject
    >;
    RecordSubmitted: TypedContractEvent<
      RecordSubmittedEvent.InputTuple,
      RecordSubmittedEvent.OutputTuple,
      RecordSubmittedEvent.OutputObject
    >;
  };
}
